# -*- coding: utf-8 -*-
"""KNN2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vi1sJ0DOUkMJ9CQNlfAsL0uWBO75_qLq
"""

import pandas as pd
import streamlit as st

st.title("KNN - Teen Mental Health Dataset")

uploaded_file = st.file_uploader("Upload file CSV", type=["csv"])

if uploaded_file is None:
    st.warning("Silakan upload file Teen_Mental_Health_Dataset.csv")
    st.stop()

st.success("File ditemukan! Memproses data...")
else:
    print("File ditemukan! Memproses data...")

# --- BAGIAN MACHINE LEARNING ---
# Membaca data
df = pd.read_csv(uploaded_file)

# Persiapan Data
features = ['age', 'daily_social_media_hours', 'sleep_hours', 'stress_level', 'anxiety_level']
X = df[features]
y = df['depression_label']

# Membagi data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model KNN
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

# Hasil
y_pred = model.predict(X_test)
print("--- Hasil Berhasil! ---")
print(f"Akurasi Model: {accuracy_score(y_test, y_pred) * 100:.2f}%")

"""kita melakukan import. Ini sama seperti menyiapkan meja kerja. Kita memanggil pandas untuk mengolah tabel data, serta sklearn (Scikit-Learn) yang berisi "pabrik" Machine Learning untuk membagi data, membuat model KNN, dan menghitung akurasi.
untuk menghindari error FileNotFoundError. Kode if not os.path.exists bertindak seperti satpam yang mengecek apakah dataset sudah ada di memori Colab. Jika belum ada, kode akan berhenti sebentar dan memunculkan tombol files.upload() agar kamu bisa memasukkan file secara langsung. Ini memastikan bahwa Python selalu tahu di mana file berada sebelum ia mencoba membacanya.
kita membaca file CSV tersebut dan mengubahnya menjadi DataFrame (tabel). Kita kemudian memisahkan data menjadi dua bagian:

Fitur (X): Kolom-kolom yang berisi "soal" atau indikator (usia, jam tidur, tingkat stres, dll).

Target (y): Kolom "jawaban" atau hasil akhir yang ingin kita prediksi (depression_label).
"""
