# -*- coding: utf-8 -*-
"""Linear Sederhana

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2WW6fD56Gz5OtzrSB02aqgqCke1mMPZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

"""Pandas & Numpy: Digunakan untuk mengolah tabel data dan perhitungan angka.

Matplotlib: "Tukang gambar" yang akan membuat grafik di akhir.

Scikit-learn (sklearn): Ini adalah library utama untuk Machine Learning. Kita mengambil modul untuk model regresi, pembagi data, dan alat ukur performa (metrics).
"""

data = {
    'jam_belajar': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'nilai_ujian': [45, 52, 58, 63, 70, 75, 82, 88, 93, 99]
}

df = pd.DataFrame(data)
print("--- Dataset Baru ---")
print(df)
print("-" * 20)

"""Data: Membuat kamus berisi pasangan input (jam_belajar) dan output (nilai_ujian).

DataFrame: Mengubah data tersebut menjadi format tabel (seperti Excel) agar mudah diproses oleh Python.
"""

X = df[['jam_belajar']]  # fitur (2D)
y = df['nilai_ujian']    # target

"""$X$ (Fitur): Variabel yang mempengaruhi hasil. Ditulis dalam kurung siku ganda [[...]] karena Scikit-learn mewajibkan input $X$ berbentuk array 2 dimensi (tabel), bukan satu baris angka saja.$y$ (Target): Variabel yang ingin kita tebak nilainya (1 dimensi)."""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""Training Set: 80% data digunakan untuk "mengajari" model.

Testing Set: 20% sisanya disimpan untuk menguji sejauh mana model bisa menebak data yang belum pernah dilihatnya.

random_state=42: Agar hasil pembagian datanya konsisten setiap kali kamu menjalankan kode.
"""

model = LinearRegression()
model.fit(X_train, y_train)

"""LinearRegression(): Memanggil otak algoritma regresi linear.

.fit(): Di sinilah proses "belajar" terjadi. Model mencari pola paling pas antara jam belajar dan nilai ujian.
"""

print("Intercept (a):", model.intercept_)
print("Koefisien (b):", model.coef_[0])

"""Intercept ($a$): Nilai dasar (prediksi nilai jika jam belajar = 0).Koefisien ($b$): Kemiringan garis. Menunjukkan seberapa besar kenaikan nilai untuk setiap tambahan 1 jam belajar."""

y_pred = model.predict(X_test)

print("\n--- Data Testing ---")
print(X_test)
print("Nilai Asli:", y_test.values)
print("Nilai Prediksi:", y_pred)

"""y_pred: Model mencoba menebak nilai berdasarkan data X_test.

MAE, MSE, RMSE: Ketiganya adalah indikator kesalahan. Semakin kecil nilainya, semakin akurat modelmu dalam memprediksi.
"""

print("\n--- Evaluasi Model ---")
print("MAE:", metrics.mean_absolute_error(y_test, y_pred))
print("MSE:", metrics.mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

"""y_pred: Model mencoba menebak nilai berdasarkan data X_test.

MAE, MSE, RMSE: Ketiganya adalah indikator kesalahan. Semakin kecil nilainya, semakin akurat modelmu dalam memprediksi.


"""

jam_baru = [[11]]
prediksi_nilai = model.predict(jam_baru)
print(f"\nPrediksi nilai untuk {jam_baru[0][0]} jam belajar: {prediksi_nilai[0]:.2f}")

"""Kamu memasukkan data baru (belajar 11 jam) untuk melihat apa hasil tebakan model.

Terakhir, bagian plt (Matplotlib) berfungsi untuk menggambar:

plt.scatter: Menggambar titik-titik data asli.

plt.plot: Menarik garis lurus (garis prediksi) yang paling optimal melewati titik-titik tersebut.
"""

plt.scatter(X, y, color='blue', label="Data Asli")
plt.plot(X, model.predict(X), color='red', label="Garis Regresi")
plt.xlabel("Jam Belajar")
plt.ylabel("Nilai Ujian")
plt.title("Regresi Linear: Jam Belajar vs Nilai Ujian")
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""Kamu memasukkan data baru (belajar 11 jam) untuk melihat apa hasil tebakan model.

Terakhir, bagian plt (Matplotlib) berfungsi untuk menggambar:

plt.scatter: Menggambar titik-titik data asli.

plt.plot: Menarik garis lurus (garis prediksi) yang paling optimal melewati titik-titik tersebut.
"""