# -*- coding: utf-8 -*-
"""Linear Logistic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h115H4J2gEjFR-7L5X0ae1o-Zxv9QhNz
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = {
    'penggunaan_data_gb': [10, 20, 5, 15, 30, 2, 8, 25, 4, 12],
    'jumlah_keluhan': [1, 0, 5, 2, 0, 8, 3, 1, 6, 2],
    'durasi_kontrak_bulan': [24, 12, 1, 6, 24, 1, 3, 18, 1, 6],
    'churn': [0, 0, 1, 0, 0, 1, 1, 0, 1, 0]
}
df = pd.DataFrame(data)
print("--- Data Pelanggan ---")
print(df.head())

X = df[['penggunaan_data_gb', 'jumlah_keluhan', 'durasi_kontrak_bulan']]
y = df['churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

import pandas as pd
model = LogisticRegression()
model.fit(X_train, y_train)

print("Intercept:", model.intercept_)
print("Koefisien:", model.coef_)

y_pred = model.predict(X_test)
print("Prediksi:", y_pred)
print("Aktual  :", y_test.values)