# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YiCeXjU7FizuaazDiI6aql-gKpENWmNS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

"""import pandas as pd: Digunakan untuk manipulasi data dalam bentuk tabel (DataFrame).

import numpy as np: Digunakan untuk operasi matematika tingkat tinggi, dalam hal ini untuk menghitung akar kuadrat (RMSE).

import matplotlib.pyplot as plt: Library utama untuk membuat visualisasi atau grafik.

from sklearn...: Mengambil modul spesifik dari scikit-learn untuk algoritma regresi, pembagian data, dan alat ukur performa model.
"""

data = {
    'pendapatan': [4, 5, 6, 8, 10, 12, 15, 20, 25, 30],
    'skor_kredit': [450, 500, 550, 600, 620, 650, 700, 750, 780, 800],
    'usia': [21, 23, 25, 30, 35, 40, 45, 50, 55, 60],
    'disetujui': [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)
print("--- Dataset Persetujuan Kredit ---")
print(df)
print("-" * 30)

"""data: Membuat dictionary berisi pasangan variabel independen (jam_belajar) dan dependen (nilai_ujian).

pd.DataFrame(data): Mengonversi dictionary tersebut menjadi tabel data yang rapi agar bisa diolah oleh library machine learning.
"""

from sklearn.model_selection import train_test_split
X = df[['pendapatan', 'skor_kredit', 'usia']]
y = df['disetujui']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LogisticRegression()
model.fit(X_train, y_train)

"""X (Fitur): Variabel input. Harus ditulis dengan kurung siku ganda [[...]] karena algoritma ini mewajibkan input dalam bentuk array 2 dimensi.

y (Target): Variabel output yang ingin kita prediksi

test_size=0.2: Artinya 20% data (2 baris) akan disimpan untuk ujian (testing), dan 80% (8 baris) digunakan untuk belajar (training).

random_state=42: Memastikan hasil pembagian data selalu sama setiap kali kode dijalankan.
LinearRegression(): Memanggil "otak" algoritma regresi linear.

.fit(): Proses belajar dimulai di sini. Model mencari hubungan linear antara jam belajar dan nilai ujian dari data training
"""

print("Intercept:", model.intercept_)
print("Koefisien (Pendapatan, Skor, Usia):", model.coef_)

"""intercept_: Titik potong sumbu Y ($a$), atau prediksi nilai jika jam belajar adalah 0.coef_: Kemiringan garis ($b$). Angka ini menunjukkan berapa kenaikan nilai setiap tambahan 1 jam belajar."""

y_pred = model.predict(X_test)

print("\n--- Hasil Uji Model ---")
print("Prediksi Model:", y_pred)
print("Data Aktual   :", y_test.values)

""".predict(): Model mencoba menebak nilai ujian untuk data testing (X_test).

Metrik Evaluasi (MAE, MSE, RMSE): Digunakan untuk mengukur seberapa meleset prediksi model dibanding nilai asli. Semakin kecil nilainya, semakin akurat model tersebut.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='green', edgecolors='black') # Menggambar titik perbandingan
plt.xlabel("Nilai Asli")
plt.ylabel("Nilai Prediksi")
plt.title("Perbandingan Nilai Asli vs Prediksi")
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""Kode ini berfungsi memvisualisasikan tingkat akurasi modelmu melalui grafik scatter plot yang membandingkan nilai asli (y_test) dengan hasil prediksi (y_pred), di mana posisi titik-titik yang semakin mendekati garis diagonal menunjukkan bahwa modelmu semakin tepat dalam menebak data."""